### ISSUE TITLE
MIRACUM Workflow compatibility

### ISSUE THREAD

**Issue by DanielAmsel** [bgruening/docker-galaxy-exome-seq#16]
Dear *,
after a chat with @wm75 , I would like to share my / our experiences within this issue.

I encountered several problems when I tried to run the [MIRACUM workflow](https://github.com/AG-Boerries/MIRACUM-Pipe/blob/master/Galaxy_Workflows/Galaxy_Workflow_MIRACUM_main.ga) on this container.
Maybe one could address the problems within this repo or create an own MIRACUM workflow fork?

Just for the sake of completeness, I would like to say that the Galaxy version could be updated to the current one.

More urgently, the following tools are missing in the build to run the workflow properly:

- [ ]  `column_arrange_by_header`
- [ ]  `SnpEff 4.3r.1`
- [ ]  `trimmomatic 0.36.5`
- [ ]  `MultiQC 1.7`
- [ ]  `varscan_somatic 2.4.3.3`
- [ ]  `samtools stats 2.0.2+galaxy1`
- [ ]  `samtool_filter2`
- [ ]  `samtools rmdup 2.0.1`
- [ ]  `samtools callmd 2.0.2`
- [ ]  `text_processing`

Tools that had to be re-installed:

- [ ] `fastqc 0.72` 

I also ran into troubles because the Workflow uses once `hg19` references and elsewhere `hg19full`. 
Downloading the genome worked for me, but not indexing with `bwa`.
So @wm75 gave me the hint, to start the container with `--priviledged`.
- [ ] Maybe one could add the `--priviledged` command to the `Usage` section of `README.md` ?

Best regards,
Daniel

**Comment by wm75** [comment]
Thanks for listing all problems in such detail! This will definitely help me to update the docker image here, but also the MIRACUM workflow using it.

**Comment by wm75** [comment]
> Tools that had to be re-installed:
> 
> * [ ]  `fastqc 0.72`

This is most likely related to https://github.com/galaxyproject/tools-iuc/pull/2406 and should be fixed automatically once the image gets rebuilt.

**Comment by DanielAmsel** [comment]
> > Tools that had to be re-installed:
> > 
> > * [ ]   `fastqc 0.72`
> 
> This is most likely related to [galaxyproject/tools-iuc#2406](https://github.com/galaxyproject/tools-iuc/pull/2406) and should be fixed automatically once the image gets rebuilt.

Ok even better. I just documented what I did, to have it running ;)

Thank you again @wm75 for all the support and the `--priviledged` advice!

**Comment by bgruening** [comment]
I triggered a rebuild. Hope that will fix it.
Have a nice weekend!

**Comment by wm75** [comment]
All above issues with the image should be fixed in the latest version. Please open new issues for remaining bugs.
